name: ci

on:
  push:
    branches:
      - "latest"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push MENDIX_ROOTFS_APP
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.MENDIX_ROOTFS_APP }}
          file: rootfs-app.dockerfile
      - name: Build and push MENDIX_ROOTFS_BUILDER
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.MENDIX_ROOTFS_BUILDER }}
          file: rootfs-builder.dockerfile
